export namespace QUERIES {
  export enum COURSE {
    PURCHASED = "Q_COURSE_PURCHASED",
    LEARNING = "Q_COURSE_LEARNING",
    GET_COURSES_DETAILS_BY_ID = "Q_COURSE_DETAILS_ID",
    FAVORITES = "Q_COURSE_FAVORITES",
    FAVORITES_IDS = "Q_COURSE_FAVORITES_IDS",
    GET_BY_ENROLLMENT_ID = "Q_COURSE_GET_BY_ENROLLMENT_ID",
    CAN_GENERATE = "Q_COURSE_CERTIFICATE",
    GET = "Q_COURSE_GET",
  }
  export enum MODULE {
    LIST = "Q_MODULE_LIST",
  }
  export enum EXAM {
    GET = "Q_EXAM_GET",
    ANSWERED = "Q_ANSWERED",
    GET_BY_ENROLLMENTID = "Q_GET_BY_ENROLLMENTID",
  }
  export enum LESSON {
    LEARNING = "Q_LEARNING",
  }
  export enum AGREEMENT_TERM {
    IS_SIGNED = "Q_AGREEMENT_TERM_IS_SIGNED",
    GET = "Q_AGREEMENT_TERM_GET",
    USER_TERMS = "Q_AGREEMENT_TERM_USER_TERMS",
  }
  export enum FEEDBACK {
    SAVE = "Q_FEEDBACK_SAVE",
    GET = "Q_FEEDBACK_GET",
    INSTRUCTOR_KPI = "Q_FEEDBACK_INSTRUCTOR_KPI",
  }
  export enum PROFILE {
    GET = "Q_GET_PROFILE",
  }
  export enum DOCUMENT {
    SENT = "Q_DOCUMENT_SENT",
    USER_STATUS = "Q_DOCUMENT_USER_STATUS",
  }
}
